### ISSUE TITLE
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV

### ISSUE THREAD

**Issue by jk-1** [dcaoyuan/nbsbt#15]
I have in  PROJECT_DIR/project/plugins.sbt:

addSbtPlugin("org.netbeans.nbsbt" % "nbsbt-plugin" % "1.1.4")

sbt is 0.13.8

I start sbt and run netbeans

> netbeans
[info] About to create NetBeans project files for your project(s).
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
	at org.netbeans.nbsbt.core.package$.setting(package.scala:66)
	at org.netbeans.nbsbt.core.NetBeans$.skipParents(NetBeans.scala:581)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply$mcZ$sp(NetBeans.scala:108)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.scala:108)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.scala:108)
	at scala.Option.getOrElse(Option.scala:120)
	at org.netbeans.nbsbt.core.NetBeans$.action(NetBeans.scala:108)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(NetBeans.scala:87)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(NetBeans.scala:87)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
[error] Use 'last' for the full log.
> last
[info] About to create NetBeans project files for your project(s).
java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
	at org.netbeans.nbsbt.core.package$.setting(package.scala:66)
	at org.netbeans.nbsbt.core.NetBeans$.skipParents(NetBeans.scala:581)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply$mcZ$sp(NetBeans.scala:108)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.scala:108)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$action$1.apply(NetBeans.scala:108)
	at scala.Option.getOrElse(Option.scala:120)
	at org.netbeans.nbsbt.core.NetBeans$.action(NetBeans.scala:108)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(NetBeans.scala:87)
	at org.netbeans.nbsbt.core.NetBeans$$anonfun$netbeansCommand$2.apply(NetBeans.scala:87)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$1$$anonfun$apply$2.apply(Command.scala:58)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:60)
	at sbt.Command$.process(Command.scala:92)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:98)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:98)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:98)
	at sbt.MainLoop$.run(MainLoop.scala:91)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:70)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:65)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:65)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:48)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:32)
	at sbt.MainLoop$.runLogged(MainLoop.scala:24)
	at sbt.StandardMain$.runManaged(Main.scala:53)
	at sbt.xMain.run(Main.scala:28)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.NoSuchMethodError: scalaz.Scalaz$.ToValidationV(Ljava/lang/Object;)Lscalaz/syntax/ValidationV;
[error] Use 'last' for the full log.

Sounds like some lib is missing or something like that?

**Comment by dcaoyuan** [comment]
Did you project's plugins contains another:
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "4.0.0")

**Comment by amitabh123** [comment]
What is the solution? I am also not able to run Netbeans and sbt (getting same error). Even new project I create gives this error. Can you please bring back ant plugin by any chance?
